spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_jpa?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345
  jpa:
    show-sql: true

logging:
  level:
    root: info
